import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from 'docx';
import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';
import type { MeetingSummary } from '../types';

// ── Markdown ──────────────────────────────────────────────

export function summaryToMarkdown(summary: MeetingSummary): string {
  const lines: string[] = ['# Meeting Summary', ''];

  lines.push('## Executive Summary', '', summary.executiveSummary, '');

  if (summary.keyDecisions.length > 0) {
    lines.push('## Key Decisions', '');
    summary.keyDecisions.forEach((d) => lines.push(`- ${d}`));
    lines.push('');
  }

  if (summary.actionItems.length > 0) {
    lines.push('## Action Items', '');
    summary.actionItems.forEach((item) => {
      let line = `- [ ] ${item.task}`;
      if (item.assignee) line += ` (${item.assignee})`;
      if (item.deadline) line += ` -- by ${item.deadline}`;
      lines.push(line);
    });
    lines.push('');
  }

  if (summary.topicsDiscussed.length > 0) {
    lines.push('## Topics Discussed', '');
    summary.topicsDiscussed.forEach((t) => lines.push(`- ${t}`));
    lines.push('');
  }

  if (summary.participants.length > 0) {
    lines.push('## Participants', '');
    summary.participants.forEach((p) => lines.push(`- ${p}`));
    lines.push('');
  }

  if (summary.followUpQuestions.length > 0) {
    lines.push('## Follow-up / Open Items', '');
    summary.followUpQuestions.forEach((q) => lines.push(`- ${q}`));
    lines.push('');
  }

  return lines.join('\n');
}

// ── Plain Text ────────────────────────────────────────────

export function summaryToPlainText(summary: MeetingSummary): string {
  const lines: string[] = ['MEETING SUMMARY', ''];

  lines.push('EXECUTIVE SUMMARY', summary.executiveSummary, '');

  if (summary.keyDecisions.length > 0) {
    lines.push('KEY DECISIONS');
    summary.keyDecisions.forEach((d) => lines.push(`  * ${d}`));
    lines.push('');
  }

  if (summary.actionItems.length > 0) {
    lines.push('ACTION ITEMS');
    summary.actionItems.forEach((item) => {
      let line = `  [ ] ${item.task}`;
      if (item.assignee) line += ` (${item.assignee})`;
      if (item.deadline) line += ` -- by ${item.deadline}`;
      lines.push(line);
    });
    lines.push('');
  }

  if (summary.topicsDiscussed.length > 0) {
    lines.push('TOPICS DISCUSSED');
    summary.topicsDiscussed.forEach((t) => lines.push(`  * ${t}`));
    lines.push('');
  }

  if (summary.participants.length > 0) {
    lines.push('PARTICIPANTS');
    summary.participants.forEach((p) => lines.push(`  * ${p}`));
    lines.push('');
  }

  if (summary.followUpQuestions.length > 0) {
    lines.push('FOLLOW-UP / OPEN ITEMS');
    summary.followUpQuestions.forEach((q) => lines.push(`  * ${q}`));
    lines.push('');
  }

  return lines.join('\n');
}

export function narrativeToMarkdown(text: string): string {
  return `# Meeting Summary\n\n${text}\n`;
}

// ── HTML (email-friendly) ─────────────────────────────────

function buildHtmlSection(title: string, items: string[], ordered = false): string {
  if (items.length === 0) return '';
  const tag = ordered ? 'ol' : 'ul';
  const listItems = items.map((i) => `<li style="margin-bottom:4px">${i}</li>`).join('');
  return `<h2 style="color:#333;font-size:16px;margin:20px 0 8px">${title}</h2><${tag} style="padding-left:20px;color:#444">${listItems}</${tag}>`;
}

export function summaryToHtml(summary: MeetingSummary): string {
  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
<body style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#222;line-height:1.6">
<h1 style="font-size:20px;color:#111;border-bottom:2px solid #8b5cf6;padding-bottom:8px">Meeting Summary</h1>
<h2 style="color:#333;font-size:16px;margin:20px 0 8px">Executive Summary</h2>
<p style="color:#444">${summary.executiveSummary}</p>`;

  html += buildHtmlSection('Key Decisions', summary.keyDecisions);

  if (summary.actionItems.length > 0) {
    const items = summary.actionItems.map((a) => {
      let text = a.task;
      if (a.assignee) text += ` <strong>(${a.assignee})</strong>`;
      if (a.deadline) text += ` <em>by ${a.deadline}</em>`;
      return text;
    });
    html += buildHtmlSection('Action Items', items);
  }

  html += buildHtmlSection('Topics Discussed', summary.topicsDiscussed);
  html += buildHtmlSection('Participants', summary.participants);
  html += buildHtmlSection('Follow-up / Open Items', summary.followUpQuestions);

  html += `<hr style="border:none;border-top:1px solid #ddd;margin:24px 0">
<p style="font-size:12px;color:#999">Generated by Meeting Summarizer &mdash; agenticsis.top</p>
</body></html>`;

  return html;
}

export function narrativeToHtml(text: string): string {
  const paragraphs = text.split(/\n\n+/).map((p) => `<p style="color:#444">${p.trim()}</p>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
<body style="font-family:Arial,Helvetica,sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#222;line-height:1.6">
<h1 style="font-size:20px;color:#111;border-bottom:2px solid #8b5cf6;padding-bottom:8px">Meeting Summary</h1>
${paragraphs}
<hr style="border:none;border-top:1px solid #ddd;margin:24px 0">
<p style="font-size:12px;color:#999">Generated by Meeting Summarizer &mdash; agenticsis.top</p>
</body></html>`;
}

// ── Word (.docx) ──────────────────────────────────────────

function docxBullets(items: string[]): Paragraph[] {
  return items.map(
    (text) =>
      new Paragraph({
        children: [new TextRun({ text, size: 22, color: '444444' })],
        bullet: { level: 0 },
        spacing: { after: 60 },
      })
  );
}

export async function summaryToDocx(summary: MeetingSummary): Promise<void> {
  const sections: Paragraph[] = [];

  sections.push(
    new Paragraph({
      text: 'Meeting Summary',
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    })
  );

  sections.push(
    new Paragraph({
      text: 'Executive Summary',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
    }),
    new Paragraph({
      children: [new TextRun({ text: summary.executiveSummary, size: 22, color: '444444' })],
      spacing: { after: 200 },
    })
  );

  if (summary.keyDecisions.length > 0) {
    sections.push(
      new Paragraph({
        text: 'Key Decisions',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 120 },
      }),
      ...docxBullets(summary.keyDecisions)
    );
  }

  if (summary.actionItems.length > 0) {
    sections.push(
      new Paragraph({
        text: 'Action Items',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 120 },
      }),
      ...summary.actionItems.map((item) => {
        let text = item.task;
        if (item.assignee) text += ` (${item.assignee})`;
        if (item.deadline) text += ` -- by ${item.deadline}`;
        return new Paragraph({
          children: [new TextRun({ text, size: 22, color: '444444' })],
          bullet: { level: 0 },
          spacing: { after: 60 },
        });
      })
    );
  }

  if (summary.topicsDiscussed.length > 0) {
    sections.push(
      new Paragraph({
        text: 'Topics Discussed',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 120 },
      }),
      ...docxBullets(summary.topicsDiscussed)
    );
  }

  if (summary.participants.length > 0) {
    sections.push(
      new Paragraph({
        text: 'Participants',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 120 },
      }),
      ...docxBullets(summary.participants)
    );
  }

  if (summary.followUpQuestions.length > 0) {
    sections.push(
      new Paragraph({
        text: 'Follow-up / Open Items',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 240, after: 120 },
      }),
      ...docxBullets(summary.followUpQuestions)
    );
  }

  sections.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Generated by Meeting Summarizer -- agenticsis.top', size: 18, color: '999999', italics: true }),
      ],
      spacing: { before: 400 },
      alignment: AlignmentType.CENTER,
    })
  );

  const doc = new Document({
    sections: [{ children: sections }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, 'meeting-summary.docx');
}

export async function narrativeToDocx(text: string): Promise<void> {
  const paragraphs = text.split(/\n\n+/).map(
    (p) =>
      new Paragraph({
        children: [new TextRun({ text: p.trim(), size: 22, color: '444444' })],
        spacing: { after: 200 },
      })
  );

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({
          text: 'Meeting Summary',
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        }),
        ...paragraphs,
        new Paragraph({
          children: [
            new TextRun({ text: 'Generated by Meeting Summarizer -- agenticsis.top', size: 18, color: '999999', italics: true }),
          ],
          spacing: { before: 400 },
          alignment: AlignmentType.CENTER,
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, 'meeting-summary.docx');
}

// ── PDF ───────────────────────────────────────────────────

function pdfAddWrappedText(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  for (const line of lines) {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function pdfAddSection(doc: jsPDF, title: string, items: string[], y: number): number {
  if (items.length === 0) return y;
  if (y > 260) { doc.addPage(); y = 20; }
  doc.setFontSize(13);
  doc.setTextColor(51, 51, 51);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(68, 68, 68);
  for (const item of items) {
    y = pdfAddWrappedText(doc, `  \u2022  ${item}`, 14, y, 180, 5.5);
    y += 1;
  }
  return y + 4;
}

export function summaryToPdf(summary: MeetingSummary): void {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setTextColor(17, 17, 17);
  doc.setFont('helvetica', 'bold');
  doc.text('Meeting Summary', 14, 20);

  doc.setDrawColor(139, 92, 246);
  doc.setLineWidth(0.5);
  doc.line(14, 24, 196, 24);

  let y = 34;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 51, 51);
  doc.text('Executive Summary', 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(68, 68, 68);
  y = pdfAddWrappedText(doc, summary.executiveSummary, 14, y, 180, 5.5);
  y += 6;

  y = pdfAddSection(doc, 'Key Decisions', summary.keyDecisions, y);

  if (summary.actionItems.length > 0) {
    const items = summary.actionItems.map((a) => {
      let text = a.task;
      if (a.assignee) text += ` (${a.assignee})`;
      if (a.deadline) text += ` -- by ${a.deadline}`;
      return text;
    });
    y = pdfAddSection(doc, 'Action Items', items, y);
  }

  y = pdfAddSection(doc, 'Topics Discussed', summary.topicsDiscussed, y);
  y = pdfAddSection(doc, 'Participants', summary.participants, y);
  y = pdfAddSection(doc, 'Follow-up / Open Items', summary.followUpQuestions, y);

  doc.setFontSize(8);
  doc.setTextColor(153, 153, 153);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Meeting Summarizer -- agenticsis.top', 105, 290, { align: 'center' });

  doc.save('meeting-summary.pdf');
}

export function narrativeToPdf(text: string): void {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setTextColor(17, 17, 17);
  doc.setFont('helvetica', 'bold');
  doc.text('Meeting Summary', 14, 20);

  doc.setDrawColor(139, 92, 246);
  doc.setLineWidth(0.5);
  doc.line(14, 24, 196, 24);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(68, 68, 68);
  pdfAddWrappedText(doc, text, 14, 34, 180, 5.5);

  doc.setFontSize(8);
  doc.setTextColor(153, 153, 153);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Meeting Summarizer -- agenticsis.top', 105, 290, { align: 'center' });

  doc.save('meeting-summary.pdf');
}

// ── Utilities ─────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    return success;
  }
}
